# permissions for end users to view multiclusterpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterpolicy-viewer-role
rules:
- apiGroups:
  - policy.submariner.io
  resources:
  - multiclusterpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.submariner.io
  resources:
  - multiclusterpolicies/status
  verbs:
  - get
