# permissions for end users to edit multiclusterpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterpolicy-editor-role
rules:
- apiGroups:
  - policy.submariner.io
  resources:
  - multiclusterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.submariner.io
  resources:
  - multiclusterpolicies/status
  verbs:
  - get
