
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - policy.submariner.io
  resources:
  - multiclusterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.submariner.io
  resources:
  - multiclusterpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - policy.submariner.io
  resources:
  - multiclusterpolicies/status
  verbs:
  - get
  - patch
  - update
