apiVersion: policy.submariner.io/v1alpha1
kind: MultiClusterPolicy
metadata:
  name: sample1
spec:
  podSelector:
    matchLabels:
      color: blue
  egress:
    - to:
      - serviceImportRefs:
        - nginx-default-cluster2 

